version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-setup:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install javascript dependencies (using Yarn)
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build ocean ds
          command: yarn build
  tests:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install javascript dependencies (using Yarn)
          command: yarn install --immutable
      - run:
          name: Run ocean ds tests
          command: yarn test

workflows:
  version: 2

  build-deploy:
    jobs:
      - build-setup
      - tests:
          requires:
            - build-setup