version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-setup:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install javascript dependencies (using Yarn)
          command: yarn install
workflows:
    build-deploy:
      jobs:
        - build-setup