version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-setup:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install javascript dependencies (using Yarn)
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build ocean ds
          command: yarn build

  tests:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install javascript dependencies (using Yarn)
          command: yarn install --immutable
      - run:
          name: Run ocean ds tests
          command: yarn test

  upload-coverage:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: yarn test --coverage
      - run:
          name: Send coverage report to Code Climate
          command: ./cc-test-reporter after-build -t lcov
          when: always

  deploy-docs:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install javascript dependencies (using Yarn)
          command: yarn install --immutable
      - run:
          name: Deploy ocean ds docs
          command: yarn deploy-storybook

workflows:
  version: 2

  build-deploy:
    jobs:
      - build-setup
      - tests:
          requires:
            - build-setup
      - deploy-docs:
          requires:
            - build-setup
