version: 2.1

orbs:
  node: circleci/node@3.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build library
          command: yarn build:lib
      - run:
          name: Build storybook
          command: yarn build:storybook
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  codestyle:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Run linter
          command: yarn lint

  commitlint:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint

  tests:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: yarn test --coverage
      - run:
          name: Send coverage report to Code Climate
          command: ./cc-test-reporter after-build -t lcov
          when: always
      - sonarcloud/scan

  deploy-pkg:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run:
          name: Bump package version by tag
          command: |
            export VERSION_TAG=$(echo $CIRCLE_TAG | awk '{print substr($1,2); }')
            yarn version --new-version $VERSION_TAG --no-git-tag-version --no-commit-hooks
      - run:
          name: Publish package
          command: |
            # Setup variables
            export VERSION_NUMBER=$(echo $CIRCLE_TAG | awk '{print substr($1,2); }')
            export TAG_NAME=$(echo $VERSION_NUMBER | grep -Po '[a-z]*')
            [ -z "$TAG_NAME" ] && TAG_NAME="latest"
            # Bump and publish
            yarn version --new-version $VERSION_NUMBER --no-git-tag-version --no-commit-hooks
            yarn publish --access public --tag $TAG_NAME

  deploy-doc:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Deploy ocean-ds documentation
          command: yarn deploy:storybook

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - codestyle:
          requires:
            - build
      - commitlint:
          requires:
            - build
      - tests:
          context: SonarCloud
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy-pkg:
          requires:
            - tests
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-doc:
          requires:
            - deploy-pkg
          filters:
            tags:
              only: /^v.*/
